/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { JournalEntryService } from "../journalEntry.service";
import { JournalEntryCreateInput } from "./JournalEntryCreateInput";
import { JournalEntry } from "./JournalEntry";
import { JournalEntryFindManyArgs } from "./JournalEntryFindManyArgs";
import { JournalEntryWhereUniqueInput } from "./JournalEntryWhereUniqueInput";
import { JournalEntryUpdateInput } from "./JournalEntryUpdateInput";
import { AiTaskFindManyArgs } from "../../aiTask/base/AiTaskFindManyArgs";
import { AiTask } from "../../aiTask/base/AiTask";
import { AiTaskWhereUniqueInput } from "../../aiTask/base/AiTaskWhereUniqueInput";

export class JournalEntryControllerBase {
  constructor(protected readonly service: JournalEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: JournalEntry })
  async createJournalEntry(
    @common.Body() data: JournalEntryCreateInput
  ): Promise<JournalEntry> {
    return await this.service.createJournalEntry({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        content: true,
        createdAt: true,
        date: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [JournalEntry] })
  @ApiNestedQuery(JournalEntryFindManyArgs)
  async journalEntries(
    @common.Req() request: Request
  ): Promise<JournalEntry[]> {
    const args = plainToClass(JournalEntryFindManyArgs, request.query);
    return this.service.journalEntries({
      ...args,
      select: {
        content: true,
        createdAt: true,
        date: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async journalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput
  ): Promise<JournalEntry | null> {
    const result = await this.service.journalEntry({
      where: params,
      select: {
        content: true,
        createdAt: true,
        date: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateJournalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput,
    @common.Body() data: JournalEntryUpdateInput
  ): Promise<JournalEntry | null> {
    try {
      return await this.service.updateJournalEntry({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          content: true,
          createdAt: true,
          date: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: JournalEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteJournalEntry(
    @common.Param() params: JournalEntryWhereUniqueInput
  ): Promise<JournalEntry | null> {
    try {
      return await this.service.deleteJournalEntry({
        where: params,
        select: {
          content: true,
          createdAt: true,
          date: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/aiTasks")
  @ApiNestedQuery(AiTaskFindManyArgs)
  async findAiTasks(
    @common.Req() request: Request,
    @common.Param() params: JournalEntryWhereUniqueInput
  ): Promise<AiTask[]> {
    const query = plainToClass(AiTaskFindManyArgs, request.query);
    const results = await this.service.findAiTasks(params.id, {
      ...query,
      select: {
        aiAgent: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        description: true,
        id: true,

        journalEntry: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/aiTasks")
  async connectAiTasks(
    @common.Param() params: JournalEntryWhereUniqueInput,
    @common.Body() body: AiTaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiTasks: {
        connect: body,
      },
    };
    await this.service.updateJournalEntry({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/aiTasks")
  async updateAiTasks(
    @common.Param() params: JournalEntryWhereUniqueInput,
    @common.Body() body: AiTaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiTasks: {
        set: body,
      },
    };
    await this.service.updateJournalEntry({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/aiTasks")
  async disconnectAiTasks(
    @common.Param() params: JournalEntryWhereUniqueInput,
    @common.Body() body: AiTaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      aiTasks: {
        disconnect: body,
      },
    };
    await this.service.updateJournalEntry({
      where: params,
      data,
      select: { id: true },
    });
  }
}
